/**
 * Single, guarded service-worker registrar.
 *
 * The worker is generated by vite-plugin-pwa (`generateSW`) and served at /sw.js.
 * It must NEVER register in development, inside an iframe, or in a Lovable
 * preview host — a cached app shell there serves stale HTML and deleted chunks.
 */

const BLOCKED_HOST_PREFIXES = ["id-preview--", "preview--"];
const BLOCKED_HOST_SUFFIXES = [
  "lovableproject.com",
  "lovableproject-dev.com",
  "beta.lovable.dev",
];

function isPreviewHost(hostname: string): boolean {
  if (BLOCKED_HOST_PREFIXES.some((prefix) => hostname.startsWith(prefix))) return true;
  return BLOCKED_HOST_SUFFIXES.some(
    (suffix) => hostname === suffix || hostname.endsWith(`.${suffix}`),
  );
}

async function unregisterAppWorkers(): Promise<void> {
  if (!("serviceWorker" in navigator)) return;
  const registrations = await navigator.serviceWorker.getRegistrations();
  await Promise.allSettled(
    registrations
      .filter((registration) => {
        const url = registration.active?.scriptURL ?? registration.installing?.scriptURL ?? "";
        return url.endsWith("/sw.js");
      })
      .map((registration) => registration.unregister()),
  );
}

export function registerServiceWorker(): void {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;

  const isRefused =
    !import.meta.env.PROD ||
    window.self !== window.top ||
    isPreviewHost(window.location.hostname) ||
    new URL(window.location.href).searchParams.has("sw") ||
    window.location.hostname === "localhost";

  if (isRefused) {
    void unregisterAppWorkers();
    return;
  }

  window.addEventListener("load", () => {
    void navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {
      /* registration failures must never break the app */
    });
  });
}
